### ISSUE TITLE
Onclick color change

### ISSUE THREAD

**Issue by tanya1810** [tanya1810/EDC-Quiz#19]
On selecting any option, change the color of that particular question label on the sidebar to green.

**Comment by ankitgoel25** [comment]
You want to make changes in index.html or index2.html?

**Comment by N15H4N7** [comment]
Is it in index.html or Index2.html ??
I can take this  @tanya1810

**Comment by ankitgoel25** [comment]
Sorry @N15H4N7 , but I asked first!

**Comment by tanya1810** [comment]
You can both take up this issue. You have to work on index.html. @ankitgoel25 @N15H4N7

**Comment by ankitgoel25** [comment]
Cool thanks! @tanya1810

**Comment by deep1112002** [comment]
I also want to work on this issue.

**Comment by jay-deep** [comment]
Can I work on this issue? I really want to contribute
