### ISSUE TITLE
Add README 

### ISSUE THREAD

**Issue by tanya1810** [tanya1810/EDC-Quiz#20]
Add a detailed readme file for my quiz web application.

**Comment by soumallyadev07** [comment]
I can take this up @tanya1810

**Comment by UshasriMavuri1999** [comment]
Hey @tanya1810 , I would like to work on this. Could you please assign this to me?

**Comment by tanya1810** [comment]
You both can work on this one. I am assigning this to both of you. @soumallyadev07 @UshasriMavuri1999

**Comment by UshasriMavuri1999** [comment]
@tanya1810 , i think pr should be verfied only after 1st october...
